morning = [
    "Hydrate",
    "Make Bed",
    "Hang",
    "Face Pulls",
    "Stretches",
    "Breathing",
    "Breakfast",
    "Teeth",
    "Mental Exercise",
    "Nature"
]

evening = [
    "Temperature",
    "Teeth",
    "Passage",
    "Plan",
    "Audio",
    "Preparation",
    "Stretches",
    "Environment"
]

[Monday]
food = ["Chicken", "Chilli"]
general = [
    "Work", "Guitar", "Racing"
]

[Tuesday]
food = ["Chicken", "Spaghetti"]
general = [
    "Work", "Guitar", "Racing"
]

[Wednesday]
food = ["Chicken", "Chicken"]
general = [
    "Work", "Guitar", "Racing"
]

[Thursday]
food = ["Chicken", "Chilli"]
general = [
    "Work", "Guitar", "Racing"
]

[Friday]
food = ["Chicken", "Spaghetti"]
general = [
    "Work", "Guitar", "Racing"
]

[Saturday]
food = ["Chicken", "Chilli"]
general = [
    "Work", "Guitar", "Racing"
]

[Sunday]
food = ["Chicken", "Spaghetti"]
general = [
    "Laundry", "Work", "Guitar", "Racing"
]
[Special]
Breathing = ["w", "[Youtube](https://www.youtube.com/watch?v=tybOi4hjZFQ 'Breathing Exercise')"]
Plan = ["p"]