date = "03/10/2022"
tomorrow = []

[morning]
Hydrate = "None"
Environment = "None"
Shoulders = "None"
Stretches = "None"
Breathing = "None"
Breakfast = "None"
Shower = "None"
Teeth = "None"
Puzzle = "None"

[evening]
Temperature = "None"
Teeth = "None"
Passage = "None"
Plan = "None"
Audio = "None"
Preparation = "None"
Stretches = "None"
Environment = "None"

[general]
Work = "None"
Guitar = "None"
Racing = "None"

[food]
Chicken = "None"
Chilli = "None"

[planned]
