morning = ["Task1", "Task2", "Writes"]

evening = ["Task3", "Task4", "Plan"]

[Monday]
food = ["Meal1", "Meal2"]
general = ["Task5"]

[Tuesday]
food = ["Meal1", "Meal2"]
general = ["Task5"]

[Wednesday]
food = ["Meal3", "Meal2"]
general = ["Task6"]

[Thursday]
food = ["Meal1", "Meal2"]
general = ["Task6"]

[Friday]
food = ["Meal1", "Meal2"]
general = ["Task6", "Task7"]

[Saturday]
food = ["Meal3", "Meal2"]
general = ["Task6", "Task7"]

[Sunday]
food = ["Meal1", "Meal2"]
general = ["Task6", "Task7"]

[Special]
#Give tasks extra details/actions by assigning a list to them

# Write a markdown string under a task with ["w","your_string"]
Writes = ["w", "This is the outputted string"]
# Plan one time events for tomorrow with ["p"], this task name should not be duplicated
Plan = ["p"]