name: Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      $PYTHONPATH: ./app
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install pylint
    - name: Lint with flake8
      working-directory: ./app
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --exit-zero --show-source --statistics
    - name: Analysing the code with pylint
      working-directory: ./app
      run: |
        pylint $(git ls-files '*.py')
